Makefile
leaf.el

Feature#12

---

Makefile
leaf.el

Feature#13

---

Makefile
Readme.org
leaf-backends.el
leaf.el

Feature#11

---

Readme.org
leaf.el

Feature#17

---

Makefile
leaf-backends.el
leaf.el

Feature#19

---

Readme.org
leaf-backends.el
leaf-tests.el
leaf.el

Feature#26

---

Readme.org
leaf-tests.el
leaf.el

Feature#28

---

Readme.org
leaf-tests.el
leaf.el

Feature#32

---

Makefile
Makefunc.mk
leaf.el

Feature#38

---

Readme.org

Fixed some English errors

---

Makefile
Makefile-check.mk
Makefunc.mk
leaf-core.el

Feature#42

---

leaf-core.el
leaf-tests.el

Feature#37

---

leaf-core.el
leaf-handler.el
leaf-tests.el

Feature#46

---

leaf-backend.el
leaf-core.el
leaf-handler.el
leaf-polyfill.el
leaf-tests.el
leaf.el

Feature#48

---

Makefile
Makefunc.mk
leaf-backend.el
leaf-core.el
leaf-handler.el
leaf-polyfill.el
leaf-tests.el
leaf.el

Feature#50

---

Readme.org
leaf-core.el
leaf-handler.el
leaf-polyfill.el
leaf-tests.el

Feature#54

---

Readme.org
leaf-core.el
leaf-handler.el
leaf-tests.el

Feature#56

---

Readme.org
leaf-core.el
leaf-handler.el
leaf-tests.el

Feature#58

---

Readme.org
leaf-core.el
leaf-handler.el
leaf-tests.el

Feature#60

---

Readme.org
leaf-core.el
leaf-handler.el
leaf-tests.el

Feature#62

---

Readme.org
leaf-core.el
leaf-handler.el
leaf-tests.el

Feature#66

---

Readme.org
leaf-core.el
leaf-handler.el
leaf-tests.el

Feature#68

---

leaf-backend.el
leaf-core.el
leaf-handler.el
leaf-polyfill.el
leaf-tests.el
leaf.el

Feature#70

---

Readme.org
leaf-core.el

Feature#72

---

Readme.org
leaf-backend.el
leaf-core.el
leaf-handler.el
leaf-polyfill.el
leaf-tests.el
leaf.el

Feature#75

---

leaf-backend.el
leaf-core.el
leaf-handler.el
leaf-tests.el

Feature#74

---

Readme.org
leaf-core.el

Feature#78

---

leaf-handler.el
leaf-tests.el
leaf.el

Feature#86

---

leaf-backend.el
leaf.el

Feature#88

---

Readme.org
leaf.el

Feature#90

---

leaf-tests.el
leaf.el

Feature#93

---

leaf-polyfill.el
leaf.el

Feature#102

---

Readme.org
leaf-tests.el
leaf.el

Feature#104

---

Readme.org
leaf-handler.el
leaf.el

Feature#106

---

README.org
leaf.el

Feature#110

---

leaf-backend.el
leaf-handler.el
leaf-polyfill.el
leaf-tests.el
leaf.el

Feature#112

---

leaf.el

Feature#117

---

README.org
leaf-tests.el
leaf.el

Feature#120

---

README.org
leaf.el

Feature#122

---

leaf.el

Feature#124

---

leaf.el

Feature#126

---

leaf.el

Feature#130

---

leaf-tests.el
leaf.el

Revert "Feature#132"

---

README.org
leaf-polyfill.el
leaf-tests.el
leaf.el

Feature#135

---

leaf.el

Feature#137

---

leaf-tests.el
leaf.el

Feature#139

---

leaf-tests.el
leaf.el

Feature#141

---

leaf.el

Feature#143

---

leaf-tests.el
leaf.el

Feature#145

---

leaf-tests.el
leaf.el

Feature#147

---

leaf-tests.el
leaf.el

Feature#149

---

leaf-polyfill.el
leaf-tests.el
leaf.el

Feature#153

---

leaf.el

Feature#155

---

leaf-tests.el
leaf.el

Feature#157

---

leaf-tests.el
leaf.el

Feature#159

---

leaf.el

Feature#161

---

leaf-tests.el
leaf.el

feature#163

---

leaf-tests.el
leaf.el

feature#165

---

leaf.el

feature#167

---

leaf-tests.el
leaf.el

feature#170

---

leaf-tests.el
leaf.el

feature#172

---

leaf.el

feature#169

---

leaf-tests.el
leaf.el

feature#175

---

leaf.el

feature#177

---

leaf.el

feature#179

---

leaf.el

feature#184

---

leaf.el

feature#188

---

leaf-tests.el
leaf.el

feature#190

---

leaf.el

feature#192

---

leaf-tests.el
leaf.el

feature#194

---

leaf.el

feature#196

---

leaf-tests.el
leaf.el

feature#198

---

leaf.el

feature#200

---

README.org
leaf-tests.el
leaf.el

feature#202

---

README.org
leaf-tests.el
leaf.el

feature #204

---

README.org
leaf-tests.el
leaf.el

feature #307

---

README.org
leaf-tests.el
leaf.el

feature#209

---

leaf.el

feature#211

---

leaf.el

feature#215

---

README.org
leaf-tests.el
leaf.el

feature#217

---

README.org
leaf-tests.el
leaf.el

feature#101

---

README.org
leaf-tests.el
leaf.el

feature#220

---

leaf.el

feature#222

---

cort-test.el
leaf-tests.el
leaf.el

feature#224

---

Makefile
leaf-tests.el
leaf.el

feature#226

---

leaf.el

feature#228

---

README.org
leaf.el

feature#230

---

leaf.el

feature#233

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.org
leaf.el

feature#235

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
leaf.el

feature#237

---

leaf.el

feature#239

---

leaf-tests.el
leaf.el

feature#241

---

leaf.el

feature#22

---

README.org
leaf.el

feature#246

---

leaf-tests.el
leaf.el

feature#245

---

leaf.el

feature#248

---

README.org
leaf.el

feature#251

---

README.org
leaf-tests.el
leaf.el

feature#253

---

README.org
leaf-tests.el
leaf.el

feature#255

---

README.org
leaf.el

feature#258

---

leaf.el

feature#260

---

README.org
leaf.el

feature#263

---

.travis.yml
CONTRIBUTING.org
Makefile
README.org
leaf.el

feature#262

---

README.org
leaf.el

feature#271

---

README.org
leaf.el

feature#274

---

leaf-tests.el
leaf.el

Add buffer local variables spesification instead of adding .dir-local.el

feature#281

---

README.org
leaf.el

feature#287

---

README.org
leaf-tests.el
leaf.el

feature#283

---

README.org
leaf-tests.el
leaf.el

Not expand autoload sexp related lambda.
Ref: #296

feature#296

---

leaf-tests.el
leaf.el

feature#295

---

leaf-tests.el
leaf.el

Not to provide leaf-tests feature.
Ref: #301

feature#301

---

README.org
leaf-tests.el
leaf.el

feature#303

---

leaf.el

feature#305

---

leaf.el

feature#308

---

leaf-tests.el
leaf.el

feature#310

---

leaf.el

feature#312

---

leaf.el

feature#314

---

Makefile
leaf-tests.el
leaf.el

feature#316

---

README.org

Typo Corrections: faether.el and feathre.el -> feather.el

---

leaf.el

feature#323

---

leaf.el

feature#319

---

leaf-tests.el
leaf.el

feature#326

---

leaf.el

feature#328

---

leaf-tests.el
leaf.el

feature#330

---

leaf-tests.el
leaf.el

feature#332

---

README.org
leaf-tests.el
leaf.el

Feature#334

---

leaf-tests.el
leaf.el

feature#336

---

README.org
leaf-tests.el
leaf.el

feature#338

---

leaf.el

feature#340

---

README.org
leaf.el

feature#342

---

README.org
leaf-tests.el
leaf.el

feature#349

---

README.org
leaf.el

feature#351

---

README.org
leaf-tests.el
leaf.el

feature#357

---

README.org
leaf.el

feature#359

---

.github/workflows/test.yml
leaf.el

feature#364

---

leaf.el

feature#366

---

README.org
leaf.el

feature#369

---

leaf.el

feature#371

---

README.org
leaf-tests.el
leaf.el

Simple implementation for `:custom*` keyword.
`:custom*` keyword issued at #361.

feature#361-pre

---

README.org
leaf-tests.el
leaf.el

feature#299

---

README.org
leaf.el

feature#377

---

README.org
leaf.el

Revert "feature#377"

---

README.org
leaf.el

feature#380

---

README.org
leaf-tests.el
leaf.el

feature#385

---

README.org
leaf-tests.el
leaf.el

feature#373

---

README.org
leaf-tests.el
leaf.el

feature#388

---

README.org
leaf-tests.el
leaf.el

feature#390

---

leaf.el

feature#392

---

README.org
leaf-tests.el
leaf.el

feature#394

---

README.org
leaf.el

feature#396

---

README.org
leaf.el

feature#398

---

leaf.el

feature#402

---

leaf-tests.el
leaf.el

feature#404

---

leaf-tests.el
leaf.el

feature#401

---

leaf.el

feature#409

---

leaf.el

feature#411

---

leaf.el

feature#413

---

leaf.el

feature#418

---

leaf-tests.el
leaf.el

feature#420

---

LICENSE
Makefile
README.org
leaf-tests.el
leaf.el

feature#422

---

README.org
leaf.el

feature#424

---

leaf-tests.el
leaf.el

feature#426

---

leaf-tests.el
leaf.el

feature#428

---

README.org
leaf.el

feature#432

---

README.org
leaf-tests.el
leaf.el

feature#435

---

leaf-tests.el
leaf.el

Fix customization comments

---

leaf-tests.el
leaf.el

done, this issue reported at #443.

feature#443

---

.github/workflows/test.yml
leaf.el

feature#447

---

README.org
leaf-tests.el
leaf.el

feature#449

---

leaf.el

feature#451

---

.github/workflows/test.yml
leaf.el

feature#455

---

README.md
README.org
leaf.el

feature#462

---

leaf-tests.el
leaf.el

add load-file-name in warning and more.

Add load-file-name in Warning and more.

---

README.md
README.org
leaf-tests.el
leaf.el

feature#471

---

README.md
README.org
leaf-tests.el
leaf.el

feature#475

---

README.md
README.org
leaf-tests.el
leaf.el

like find-function, but in leaf block.

Added support to find the leaf block.

---

leaf.el

feature#477

---

leaf-tests.el
leaf.el

feature#479

---

leaf-tests.el
leaf.el

Let the leaf-key-describe-bindings with a path

---

leaf.el

``` 
(leaf foo-bar)
(leaf foo)
```
`leaf-find foo` will jump to foo-bar block

fix leaf-find-regexp.

---

README.md
README.org
leaf-tests.el
leaf.el

Add :bind-keymap, :bind-keymap* keywords.
Those keywords are suggested at #266

Add :bind-keymap, :bind-keymap* keywords

---

leaf-tests.el
leaf.el

feature#482

---

README.md
README.org
leaf-tests.el
leaf.el

Add :setf, :push, :pre-setf, :pre-push keywords
:setf is suggested at #470.

Add :setf, :push, :pre-setf, :pre-push keywords

---

README.md
leaf.el

feature#486

---

leaf-tests.el
leaf.el

feature#494

---

Makefile
leaf-tests.el
leaf.el

Fix leaf find in embedded leaf block 2

---

leaf.el

Add :added document keyword.
This keyword is suggested at https://github.com/conao3/leaf-keywords.el/issues/145

Add :added document keyword

---

.github/workflows/test.yml

Run test also on Emacs-27.2

---

README.org
leaf-tests.el
leaf.el

Add :vc keyword

---

README.md

add :vc document
